notifications:
  email: false
git:
  depth: 1
matrix:
  include:
  - os: osx
    osx_image: xcode8.3
install:
- travis/install.sh
script:
- travis/build.sh
deploy:
  provider: releases
  api_key:
    secure: Jy0aRoTHAxseVP0qy/NC+PBf/N1hnE0+33Vx0soP8IxBzfRsRIYbnY5LH+7PzHa6LMvzclvN7YqMSYUl0ODO1LRTnJ/aZ8sRPlUj9K5IY6utOryje+rbNIKuO6kSXwaJQOARXDyNH+EAyC/MkyIlSVTEQX4Ke0CyfVmZNtHkVLwyQ4a7ykWLKHur6Zr5MySF4+Rgj9K+zvodUBUOPrzZEEO56JC+ae6MLPBC5KMILa0W4YlkVKuUFp1LsA65KBLbSTx1pGr990//8QnQkSr1CubNWFFFYCCMeWMD/vVk2W6JlxsVR8tjJDU1gddVqXmFuRkY94ZGNvf2vwwos+sEHKsMQiL/ga+wXHIUZs/ogiZG3HIpF6tsf+kkWj4m4KrzosTJCCWBOIUH/kBqSA9uEOnNBDhxPwJbMpTgx2j4y2Sbh5OuE+XWs5dy25zCkavJH4TckGf+NK+FWClJR6ktzCaSP/qeJ5JqB6gMuRwFkUlXSbh3kZe3hP98pQ9CaUnM3VEt1ekhxM0jDHi9dHuXH9zlH2+Sy5qrwhq9a2HhkJoLSNiu+xuZA+hHBvNceLaujLqqEyaXCm2SQDVGFQKoORSbLX2dwCXvq6FsoiWJx39JeH7XWgAvy0A2W9bmunSH0BOydx21cKG6GCvAWiU2b3v5SQKLgc7TtnQw2faS+5Q=
  file_glob: true
  file: builder/dmg/*.dmg
  skip_cleanup: true
  overwrite: true
  draft: true
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_90b7c842d9ac_key -iv $encrypted_90b7c842d9ac_iv -in travis/codesign/PrivKey.p12.enc -out travis/codesign/PrivKey.p12 -d
