skip_non_tags: true

install:
  # Update the submodule
  - git submodule update --init

  # Install NSIS
  - appveyor DownloadFile "https://sourceforge.net/projects/nsis/files/latest/download?source=files" -FileName nsis.exe
  - nsis.exe /S

  # Get bazaar and clone the translations repo
  - pip install bzr
  - bzr checkout --lightweight lp:~sabnzbd/sabnzbd/0.8.x.tr

  # Remove unwanted translations
  - cd 0.8.x.tr
  - del /S en*.po
  - del /S pt.po
  - del /S ar.po
  - del /S ja.po
  - del /S th.po
  - del /S lo.po
  - del /S hy.po
  - del /S hu.po
  - del /S hr.po
  - del /S cy.po
  - del /S cs.po
  - del /S *.pot
  - cd ..

  # Copy the translations
  - xcopy 0.8.x.tr\po builder\src\po /e /y

  # Get virtualenv
  - pip install virtualenv --upgrade

  # Create 2 virtual envs and install requirements
  # > Win64
  - virtualenv -p C:\\Python27-x64\python.exe win64
  - win64\Scripts\activate.bat
  - python -c "import sys; print(sys.version)"
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade -r appveyor/requirements_win.txt
  - deactivate
  # > Win32
  - virtualenv -p C:\\Python27\python.exe win32
  - win32\Scripts\activate.bat
  - python -c "import sys; print(sys.version)"
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade -r appveyor/requirements_win.txt
  - deactivate

build_script:
  # Move to right directory
  - cd builder

  # We need to set the PATH for every virtualenv
  # > Win64
  - ..\win64\Scripts\activate.bat
  - set PATH=C:\projects\sabbuild\builder\src\win\7zip;C:\Program Files (x86)\NSIS\Unicode;%PATH%
  - python package.py installer
  - deactivate
  # > Win32
  - ..\win32\Scripts\activate.bat
  - set PATH=C:\projects\sabbuild\builder\src\win\7zip;C:\Program Files (x86)\NSIS\Unicode;%PATH%
  - python package.py installer

  # Make the installer (from 32bit, to be sure)
  - python make_windows_installer.py

  # Make the source package and stop
  - python package.py source
  - deactivate

artifacts:
  - path: builder\src\*-win-setup.exe
    name: Installer
  - path: builder\src\*-win32-bin.zip
    name: BinaryWin32
  - path: builder\src\*-win64-bin.zip
    name: BinaryWin64
  - path: builder\src\*-src.tar.gz
    name: Source

deploy:
  description: DO NOT USE THESE FILES UNLESS INSTRUCTED TO DO SO!
  provider: GitHub
  auth_token:
    secure: ogVX+nbG6hCMHgHBul09PAMZ0I9979OoeRGmeHLxojXkZnAPLv+dfOI38emFr5dw
  draft: false
  prerelease: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
