notifications:
  email: false

install:
  # Update the submodule
  - git submodule update --init

  # Install NSIS
  - appveyor DownloadFile "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/unsis/nsis-2.46.5-Unicode-setup.exe" -FileName nsis.exe
  - nsis.exe /S

  # Set the path to include NSIS and 7zip
  - set PATH="C:\projects\sabbuild\builder\src\win\7zip";"C:\Program Files (x86)\NSIS\Unicode";%PATH%

  # Update pip and get virtualenv
  - pip install virtualenv --upgrade

  # Create 2 virtual envs and install requirements
  # > Win32
  - virtualenv -p C:\\Python27\python.exe win32
  - win32\Scripts\activate.bat
  - python --version
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade -r appveyor/requirements_win.txt
  - deactivate
  # > Win64
  - virtualenv -p C:\\Python27-x64\python.exe win64
  - win64\Scripts\activate.bat
  - python --version
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade -r appveyor/requirements_win.txt
  - deactivate

build_script:
