notifications:
  email: false

install:
  # Install NSIS
  - appveyor DownloadFile "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/unsis/nsis-2.46.5-Unicode-setup.exe" -FileName nsis.exe
  - nsis.exe /S

  # Update pip and get virtualenv
  - pip install virtualenv --upgrade

  # Create 2 virtual envs and install requirements
  # > Win32
  - virtualenv -p C:\\Python27\python.exe win32
  - win32\Scripts\activate.bat
  - pip install --upgrade -r requirements.txt
  - deactivate
  # > Win64
  - virtualenv -p C:\\Python27-x64\python.exe win64
  - win64\Scripts\activate.bat
  - pip install --upgrade -r requirements.txt
  - deactivate

build_script:
  # Update the submodule
  - git submodule update --init